version: "3.3"

services:
  postgres:
    image: postgres:15
    container_name: efcore_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FreelanceDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: anncarln/freelance-service-manager:latest
    container_name: freelance_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=FreelanceDb;Username=postgres;Password=postgres
volumes:
  pgdata:
