name: .NET Build and Test

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: FreelanceDb
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U postgres" 
                    --health-interval 10s
                    --health-timeout 5s 
                    --health-retries 5
        
        env:
            ASPNETCORE_ENVIRONMENT: Development
            ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=FreelanceDb;Username=postgres;Password=postgres"

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Run tests
              run: dotnet test --no-build --verbosity normal